sudo: required
dist: focal
language: python
python:
  - "3.8"
env:
  global:
  - ROLE_NAME: softether-vpn
  - secure: s5xiQN55eIt1J9wvE8Rwgem1p97eiXeOwDDG4cubHXQ+H42m3oquGGlbG2EXEdkq1Of3JFUHcbi8ZsXmoAiZCcPp3DHVsIG6LGR3XZhUWvuL/hqaKTGiy/ViClosLImpco5Zc+Eo4loQP+OUrlOnVPU5P9AHSDjQW21OMd/TMsdGIolgaE1gUEi4NsOGLf1+OdOcAEptmKdSTf+f0O+wEPNgOsa+1EpooCOsS9nIcwsNPdBTbqFXSgLa0l0JkMAvwcgZOFjQR46to8PC+mWmkIiHbWt90jD6jxluU1ezPl5ckTl7zq69vk+lZGYzzhCZamsCrIYWLMwmRgjlC0V4ZOw+ftKe0ohOXvvHI9yxkufer12noovGhNfkKyAXDKi47rpXGl/4n1r0J4cJjd3rVYHVmtUkBc+oo+5jKDGgtMLI9Vh5ejbCjhC4yjdHDZMc5np27MJOd1/WrKISZtqEoN+KGHcTAFaA0v/Ib53zl+kSg9oAhk0d/720nKR3oZY16JlqvYxL/VqgSGY90XKI69l97SwixQLoH930/B7JhXBT2FlUcRA/lqe1opP59SJJUoeQrQChaOoc6r9+8EuDwGQtxZFLketHlvxwnKIB3OExraBdRgvZyMuXKbL63EjxdkWfZMTROKX72SVOOPCiltxuGKuDgmgbpb/eoeFnwn0=
  - secure: 7Oe4q6tDm3cxJ8Qdy+Dn9T8TqKiWI6JE6kE/ddMM9IHFR5AlJq08sdOFGj53xmzpEJDj3bgj/5oiDNNiUyIPnV59SdCDFgcjce340H6L9H+v9qIb2hQauF01ppPc4JzywhwRgIFJevfC/lqD9m7NarXSTl8mWE9WQjNxDQstza+jTiy2vt1UK3v+ZgI9kfCwoQhD+0OE6d10V59IoAvpoc/CgSbPd2HY5l45rToz5b8TAS+CcxoUaZ1LhG7DGu+u91+FEkXFO3iMBioGc3NS+kFIphpmKUcnE2H/Yk7eTIoD+p6wjw5mYZEVa5mcQxsCs4HtBHQiSSJyymABf5/aDr8agzrhaPNuaabnW9L9zQp3atPoKJ3xYA1AjZAgLqDY0D554gFnDc6EBxvuKESjTDnI3/hpKEPJNv5g5hYPOwF0hYJFWyIfpFVcWBs4ShpoJelaUb4xOoUN8C/XrNhQYkeh/zllZUQFu0LKndN7A+1PI4KWaq7atDf67XmN1YJszYPiiFYBZdDdwrKcuKsmGBB8BLXky0H/icGa9hxebu4slkfz2uRR5QPNRvoGsfJWJCN36HJRJKfherxStwOqIcshPzzSogKleR5OvsXhdHnlNNSRSbzvIeZp/t3Un7l7aZBhenS0Hvi0NfriacW7RfhKxZrXHuXQAmAh/60Oj+0=
  jobs:
  - MOLECULE_DISTRO: centos8
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: ubuntu2004
  - MOLECULE_DISTRO: ubuntu1804
  - MOLECULE_DISTRO: debian10
  - MOLECULE_DISTRO: debian9
services: docker
install:
- pip install molecule-docker yamllint ansible-lint
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#- cd ../
#- GALAXY_ROLE_NAME=$(echo "${ROLE_NAME}" | tr '-' '_')
#- mv ansible-role-$ROLE_NAME hybridadmin.$GALAXY_ROLE_NAME
#- cd hybridadmin.$GALAXY_ROLE_NAME
script:
- molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
