dependency:
  name: galaxy
driver:
  name: docker
#lint: |
#  set -e
#  yamllint .
#  ansible-lint -c molecule/default/yaml-lint.yml
platforms:
  - name: ansible-role-exabgp-${MOLECULE_DISTRO}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  options:
    v: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      timeout: 60
verifier:
  name: ansible
  enabled: false
