---
- name: Converge
  hosts: all
  vars:
    softether_fqdn: "vpn.chikomo.net"
    generate_ssl_cert: false
    option_add_to_path: true
    certbot_certs:
      - email: "janedoe@example.com"
        domains:
          - "{{ softether_fqdn }}"
    my_softether_vpn_users:
      - {
        name: "tinashe",
        password: "a5ZQtcgSR2"
      }
    my_softether_ipsec_presharedkey: "[1KH;+r-X#cvhpv7Y6=#;[{u"
    softether_version: "4.32-9731"
    softether_location: /opt
    softether_vpn_users: "{{ my_softether_vpn_users }}"
    softether_ipsec_presharedkey: "{{ my_softether_ipsec_presharedkey }}"
    softether_option_securenat: true
    softether_option_bridge: false
    # ============== IPSEC ===================
    softether_option_ipsec: true
    softether_ipsec_l2tp: yes
    softether_ipsec_l2tpraw: yes
    softether_ipsec_etherip: no
    # /============== IPSEC ===================
    # ============== OPENVPN ===================
    softether_option_openvpn: true
    softether_openvpn_port: 1194
    softether_openvpn_config: "{{ softether_home }}/generated/openvpn_config.zip"
    # /============== OPENVPN ===================
    # ============== Bridge ===================
    softether_bridge_device: soft
    softether_bridge_tap: no
    # ============== /Bridge ===================

  pre_tasks:
    - debug: msg="Pre tasks section for {{ ansible_host }}"

    - name: get remote host ip
      set_fact:
        remote_ip_address: "{{ ansible_host }}"

  roles:
     - {
        role: "ansible-role-softether-vpn"
       }
